feat: claude support

diff --git a/per b/per
--- a/per
+++ b/per
@@ -1,16 +1,32 @@
 #!/bin/bash
-# TODO: choose context
-ALL_ARGS="$*"
-
 MODEL="sonar"
 SEARCH_CONTEXT_SIZE="medium"
+BASE_URL="https://api.perplexity.ai"
+API_KEY=$PERPLEXITY_API_KEY
+AI="Perplexity"
+
+# Error trapper
+trap 'echo "Error on line $LINENO"' ERR
 
 get_new_history_file() {
   HISTORY="$HOME/.perplexity-auto-history-$(date +%Y-%m-%d-%H-%M-%S)"
 }
 
-while getopts 'hdpu:lLnrRs' opt; do
+while getopts 'hdpu:lLnrRsc:' opt; do
   case "$opt" in
+    c)
+      BASE_URL="https://api.anthropic.com/v1"
+
+      if [ "$OPTARG" == "3.5" ]; then
+        MODEL="claude-3-5-haiku-latest"
+      else
+        MODEL="claude-3-7-sonnet-latest"
+      fi
+
+      SEARCH_CONTEXT_SIZE=""
+      API_KEY=$CLAUDE_API_KEY
+      AI="Claude"
+      ;;
     h)
       SEARCH_CONTEXT_SIZE="high"
       ;;
@@ -97,28 +113,32 @@ DATA="
   ]
 }"
 
-REQUEST=$(gum spin --spinner dot --title "Perplexity is thinking..." -- curl --silent --location 'https://api.perplexity.ai/chat/completions' \
+RESPONSE=$(gum spin --spinner dot --title "$AI is thinking..." -- curl --silent --location "$BASE_URL/chat/completions" \
 --header 'accept: application/json' \
 --header 'content-type: application/json' \
---header "Authorization: Bearer $PERPLEXITY_API_KEY" \
+--header "Authorization: Bearer $API_KEY" \
 --data "$DATA")
 
-if echo "$REQUEST" | jq -e ".error"
+if echo "$RESPONSE" | jq -e ".error"> /dev/null 2>&1;
 then
-  echo "$REQUEST" | jq ".error" > /dev/stderr
+  echo "$RESPONSE" | jq ".error" > /dev/stderr
   exit 1
 fi
 
-# To show citation like "[1] website" we need to put number between [] and do +1 from the key
-CITATIONS=$(echo "$REQUEST" | jq -r '.citations | to_entries | map("[" + ((.key + 1) | tostring) + "] " + .value) | join("\n")')
-CONTENT=$(echo "$REQUEST" | jq -r '.choices.[0].message.content')
-echo "# Citations" | glow
-# Disable width wrapping
-echo "$CITATIONS" | glow --width 0
+if [ "$AI" == "Perplexity" ]; then
+  # To show citation like "[1] website" we need to put number between [] and do +1 from the key
+  CITATIONS=$(echo "$RESPONSE" | jq -r '.citations | to_entries | map("[" + ((.key + 1) | tostring) + "] " + .value) | join("\n")')
+  echo "# Citations" | glow
+  # Disable width wrapping
+  echo "$CITATIONS" | glow --width 0
+fi
+
+CONTENT=$(echo "$RESPONSE" | jq -r '.choices.[0].message.content')
+
 echo "# Results" | glow
 # Disable width wrapping
 echo "$CONTENT" | glow --width 0
 
-MESSAGE=$(echo "$REQUEST" | jq -r '.choices.[0].message')
+MESSAGE=$(echo "$RESPONSE" | jq -r '.choices.[0].message')
 
 echo "$PROMPT,$MESSAGE," >> "$HISTORY"
